### ISSUE TITLE
How to get built-in LiveReload to work

### ISSUE THREAD

**Issue by petethedude** [rwjblue/broccoli-timepiece#9]
Is there a way to get LiveReload working with broccoli-timepiece? I'm trying to set broccoli up for a project, but I don't want to use `broccoli serve`, because I want to link my CSS up to `http://localhost:4200/assets/css/styles.css` just for development. I thought broccoli-timepiece seemed like a good alternative, but then I lose LiveReload. Any suggestions or documentation I could reference?

**Comment by rwjblue** [comment]
If you want serving of assets, then you likely do not want to use this library (instead use `broccoli serve`).

**Comment by fredrikekelund** [comment]
@rwjblue I'd like to raise this question again.

I'm running a dev set-up where Broccoli deals with my front-end assets, and nginx routes requests to `/php` to a directory outside of the stuff that Broccoli touches. Using broccoli-timepiece makes a lot of sense, because I can retain this structure and let nginx route requests to my back-end properly (which isn't possible with `broccoli serve`).

I tried thinking of a solution of how I could integrate this in my Brocfile, but then I'd have to create a new tiny-lr server for every build, which seems inefficient, and it feels like the wrong place to deal with functionality like that anyway.

Would integrating tiny-lr into broccoli-timepiece be an option? I could go though some hoops in my JS to determine where to send the requests to my back-end too (like if domain is `localhost`, send to `myapp.dev`), but I feel a bit like then I'd be moving part of my build logic into my actual app. It imagine this set-up is fairly common, and allowing for using livereload with it would be really cool.

**Comment by fredrikekelund** [comment]
Bump, any chance to see LiveReload integrated?
